# Generated by Django 5.1.2 on 2024-11-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT'), ('AI', 'AI'), ('Mobile Phones', 'Mobile Phones')], max_length=100),
        ),
    ]
